def traaducaoapp(language_of_page):
    textos = {}

    if language_of_page == "PORTUGUÊS":
        textos = {
            'LANCAMENTOS LOCALIZADOS': 'LANÇAMENTO(S) LOCALIZADO(S), DESEJA ALTERAR?',
            'INATIVAS_TEXT':'INATIVAS',
            'ATIVAS_TEXT':'ATIVAS',
            'SELECIONAR_A_ID_TEXT':'SELECIONAR A ID',
            'ATIVAR_TEXT':'ATIVAR',
            'NOVA_CONTA_BANCÁRIA_TEXT':'NOVA CONTA BANCÁRIA',
            'NOME_TEXT':'NOME',
            'PROPRIETÁRIO_TEXT':'PROPRIETÁRIO',
            'INSERIR_TEXT':'INSERIR',
            'INATIVAR_TEXT':'INATIVAR',
            'EDITAR_CONTA_BANCÁRIA_TEXT':'EDITAR CONTA BANCÁRIA',
            'NOME_BANCO_TEXT':'NOME',
            'NOVA_CONTA_BANCÁRIA_TEXT':'NOVA CONTA BANCÁRIA',
            'NOVA_CONTA_CONTÁBIL_TEXT':'NOVA CONTA CONTÁBIL',
            'NOVO_PROJECT_TEXT':'NOVO PROJETO/EVENTO',            
            'CONTA_CONTÁBIL_TEXT':'CONTA CONTÁBIL',
            'CATEGORIA_TEXT':'CATEGORIA',
            'ATRIBUIÇÃO_TEXT':'ATRIBUIÇÃO',
            'EDITAR_CONTA_CONTÁBIL_TEXT':'EDITAR CONTA CONTÁBIL',
            'EDITAR_PROJETO_EVENTO_TEXT':'EDITAR PROJETO/EVENTO',
            'NOVO_CARTÃO_DE_CRÉDITO_TEXT':'NOVO CARTÃO DE CRÉDITO',
            'EDITAR_CARTÃO_DE_CRÉDITO_TEXT':'EDITAR CARTÃO DE CRÉDITO',
            'CONTASBANCARIASTEXT':'CONTAS BANCÁRIAS',
            'CONTASCONTABEISTEXT':'CONTAS CONTÁBEIS',
            'PROJETOS/EVENTOSTEXT':'PROJETOS/EVENTOS',
            'CARTOES_DE_CREDITOTEXT':'CARTÕES DE CRÉDITO',
            'INSERINDO_INFORMAÇÕESTEXT' : 'INSERINDO INFORMAÇÕES',
            'DATA_SALDOTEXT' :'DATA SALDO',
            'SALDO_ATUALTEXT' :'SALDO ATUAL:',
            'RECEITASTEXT' :'RECEITAS:',
            'FILTRAR_PROPRIETÁRIOTEXT' :'FILTRAR POR PROPRIETÁRIO',
            'SELECIONE UM PROPRIETÁRIOTEXT' :'SELECIONE UM PROPRIETÁRIO',
            'SALDOS_BANCÁRIOSTEXT' :'SALDOS BANCÁRIOS',
            'SALDO_TOTALTEXT' :'SALDO TOTAL:',
            'SALDO ACUMULADO NO FIM DE CADA MÊSTEXT' :'SALDO ACUMULADO NO FIM DE CADA MÊS',
            'AJUSTAR_SALDOTEXT' :'AJUSTAR SALDO',
            'MOSTRAR TODAS AS CONTASTEXT' :'MOSTRAR TODAS AS CONTAS',
            'Inserir_novo_registroTEXT': 'Inserir novo registro',
            'DATATEXT': 'DATA',
            'SELECIONE_O_BANCOTEXT': 'SELECIONE O BANCO',
            'SELECIONE_O_LANÇAMENTOTEXT': 'SELECIONE O LANÇAMENTO',
            'INSIRA_O_VALORTEXT': 'INSIRA O VALOR',
            'ESTORNOTEXT': 'ESTORNO',
            'DESCRIÇÃOTEXT': 'DESCRIÇÃO',
            'SELECIONE_O_PROJETOTEXT': 'SELECIONE O PROJETO',
            'CONCILIADOTEXT': 'CONCILIADO',
            'ANALÍTICATEXT': 'ANALÍTICA',
            'INSERIRTEXT': 'INSERIR',
            'Preencha_todos_os_camposTEXT': 'Preencha todos os campos',
            'Registro_inserido_com_sucessoTEXT': 'Registro inserido com sucesso!',
            'Editar_registroTEXT': 'Editar registro',
            'INSERIR_NOVO_LANÇAMENTOTEXT': 'INSERIR NOVO LANÇAMENTO',
            'Digite_o_IDTEXT': 'Digite o ID',
            'EDITARTEXT': 'EDITAR',
            'DELETARTEXT': 'DELETAR',
            'Registro_deletado_com_sucessoTEXT': 'Registro deletado com sucesso!',
            'Registro_editado_com_sucessoTEXT': 'Registro editado com sucesso!',
            'Inserir_nova_transferência_entre_contasTEXT': 'Inserir nova transferência entre contas',
            'SELECIONE_O_BANCO_DE_ORIGEMTEXT': 'SELECIONE O BANCO DE ORIGEM',
            'SELECIONE_O_BANCO_DE_DESTINOTEXT': 'SELECIONE O BANCO DE DESTINO',
            'Selecione_contas_diferentesTEXT': 'Selecione contas diferentes',
        }

    elif language_of_page == "ENGLISH":
        textos = {
            'LANCAMENTOS LOCALIZADOS': 'RECORDS FOUND, DO YOU WANT TO CHANGE?',
            'INATIVAS_TEXT':'INACTIVE',
            'ATIVAS_TEXT':'ACTIVE',
            'SELECIONAR_A_ID_TEXT':'SELECT ID',
            'ATIVAR_TEXT':'ACTIVATE',
            'NOVA_CONTA_BANCÁRIA_TEXT':'NEW BANK ACCOUNT',
            'NOME_TEXT':'NAME',
            'PROPRIETÁRIO_TEXT':'OWNER',
            'INSERIR_TEXT':'ENTER',
            'INATIVAR_TEXT':'INACTIVATE',
            'EDITAR_CONTA_BANCÁRIA_TEXT':'EDIT BANK ACCOUNT',
            'NOME_BANCO_TEXT':'NAME BANK',
            'NOVA_CONTA_BANCÁRIA_TEXT':'NEW BANK ACCOUNT',
            'NOVA_CONTA_CONTÁBIL_TEXT':'NEW ACCOUNTING ACCOUNT',
            'NOVO_PROJECT_TEXT':'NEW PROJECT/EVENT',
            'CONTA_CONTÁBIL_TEXT':'ACCOUNTING ACCOUNT',
            'CATEGORIA_TEXT':'CATEGORY',
            'ATRIBUIÇÃO_TEXT':'ASSIGNMENT',
            'EDITAR_CONTA_CONTÁBIL_TEXT':'EDIT ACCOUNTING ACCOUNT',
            'EDITAR_PROJETO_EVENTO_TEXT':'EDIT PROJECT/EVENT',
            'NOVO_CARTÃO_DE_CRÉDITO_TEXT':'NEW CREDIT CARD',
            'EDITAR_CARTÃO_DE_CRÉDITO_TEXT':'EDIT CREDIT CARD',
            'CONTASBANCARIASTEXT':'BANK ACCOUNTS',
            'CONTASCONTABEISTEXT':'ACCOUNTING ACCOUNTS',
            'PROJETOS/EVENTOSTEXT':'PROJECTS/EVENTS',
            'CARTOES_DE_CREDITOTEXT':'CREDIT CARDS',
            'INSERINDO_INFORMAÇÕESTEXT' : 'INSERTING DATA',
            'DATA_SALDOTEXT' :'DATE BALANCE',
            'SALDO_ATUALTEXT' :'CURRENT BALANCE:',
            'RECEITASTEXT' :'REVENUES:',
            'FILTRAR_PROPRIETÁRIOTEXT' :'FILTER BY OWNER',
            'SELECIONE UM PROPRIETÁRIOTEXT' :'SELECT AN OWNER',
            'SALDOS_BANCÁRIOSTEXT' :'BANK BALANCES',
            'SALDO_TOTALTEXT' :'TOTAL BALANCE:',
            'SALDO ACUMULADO NO FIM DE CADA MÊSTEXT' :'CUMULATIVE BALANCE AT THE END OF EACH MONTH',
            'AJUSTAR_SALDOTEXT' :'ADJUST BALANCE',
            'MOSTRAR TODAS AS CONTASTEXT' :'SHOW ALL ACCOUNTS',
            'Inserir_novo_registroTEXT': 'Insert new ENTRY',
            'DATATEXT': 'DATE',
            'SELECIONE_O_BANCOTEXT': 'SELECT BANK',
            'SELECIONE_O_LANÇAMENTOTEXT': 'SELECT ENTRY',
            'INSIRA_O_VALORTEXT': 'ENTER VALUE',
            'ESTORNOTEXT': 'REVERSAL',
            'DESCRIÇÃOTEXT': 'DESCRIPTION',
            'SELECIONE_O_PROJETOTEXT': 'SELECT PROJECT',
            'CONCILIADOTEXT': 'CONCILIATED',
            'ANALÍTICATEXT': 'ANALYTICS',
            'INSERIRTEXT': 'INSERT',
            'Preencha_todos_os_camposTEXT': 'Fill in all fields',
            'Registro_inserido_com_sucessoTEXT': 'Record inserted successfully!',
            'Editar_registroTEXT': 'Edit record',
            'INSERIR_NOVO_LANÇAMENTOTEXT': 'INSERT NEW ENTRY',
            'Digite_o_IDTEXT': 'Enter ID',
            'EDITARTEXT': 'EDIT',
            'DELETARTEXT': 'DELETE',
            'Registro_deletado_com_sucessoTEXT': 'Record deleted successfully!',
            'Registro_editado_com_sucessoTEXT': 'Record edited successfully!',
            'Inserir_nova_transferência_entre_contasTEXT': 'Insert new transfer between accounts',
            'SELECIONE_O_BANCO_DE_ORIGEMTEXT': 'SELECT SOURCE BANK',
            'SELECIONE_O_BANCO_DE_DESTINOTEXT': 'SELECT DESTINATION BANK',
            'Selecione_contas_diferentesTEXT': 'Select different accounts',
        }

    elif language_of_page == "РУССКИЙ":
        textos = {
            'LANCAMENTOS LOCALIZADOS': 'РЕЛИЗОВ, ХОТИТЕ ИЗМЕНИТЬ?',
            'INATIVAS_TEXT':'НЕАКТИВНЫЙ',
            'ATIVAS_TEXT':'АКТИВНЫЙ',
            'SELECIONAR_A_ID_TEXT':'ВЫБЕРИТЕ ИДЕНТИФИКАТОР',
            'ATIVAR_TEXT':'АКТИВИРОВАТЬ',
            'NOVA_CONTA_BANCÁRIA_TEXT':'НОВЫЙ БАНКОВСКИЙ СЧЕТ',
            'NOME_TEXT':'ИМЯ',
            'PROPRIETÁRIO_TEXT':'ВЛАДЕЛЕЦ',
            'INSERIR_TEXT':'ВСТАВЛЯТЬ',
            'INATIVAR_TEXT':'ДЕАКТИВИРОВАТЬ',
            'EDITAR_CONTA_BANCÁRIA_TEXT':'ИЗМЕНИТЬ БАНКОВСКИЙ СЧЕТ',
            'NOME_BANCO_TEXT':'НАЗВАНИЕ БАНКА',
            'NOVA_CONTA_BANCÁRIA_TEXT':'НОВЫЙ БАНКОВСКИЙ СЧЕТ',
            'NOVA_CONTA_CONTÁBIL_TEXT':'НОВЫЙ БУХГАЛТЕРСКИЙ СЧЕТ',
            'NOVO_PROJECT_TEXT':'НОВЫЙ ПРОЕКТ/СОБЫТИЕ',            
            'CONTA_CONTÁBIL_TEXT':'БУХГАЛТЕРСКИЙ СЧЕТ',
            'CATEGORIA_TEXT':'КАТЕГОРИЯ',
            'ATRIBUIÇÃO_TEXT':'АТРИБУЦИЯ',
            'EDITAR_CONTA_CONTÁBIL_TEXT':'РЕДАКТИРОВАТЬ БУХГАЛТЕРСКИЙ СЧЕТ',
            'EDITAR_PROJETO_EVENTO_TEXT':'РЕДАКТИРОВАТЬ ПРОЕКТ/СОБЫТИЕ',
            'NOVO_CARTÃO_DE_CRÉDITO_TEXT':'НОВАЯ КРЕДИТНАЯ КАРТА',
            'EDITAR_CARTÃO_DE_CRÉDITO_TEXT':'ИЗМЕНИТЬ КРЕДИТНУЮ КАРТУ',
            'CONTASBANCARIASTEXT':'БАНКОВСКИЕ СЧЕТА',
            'CONTASCONTABEISTEXT':'БУХГАЛТЕРСКИЕ СЧЕТА',
            'PROJETOS/EVENTOSTEXT':'ПРОЕКТЫ/СОБЫТИЯ',
            'CARTOES_DE_CREDITOTEXT':'КРЕДИТНЫЕ КАРТЫ',
            'INSERINDO_INFORMAÇÕESTEXT' : 'ВСТАВКА ИНФОРМАЦИИ',
            'DATA_SALDOTEXT': 'ДАТА БАЛАНСА',
            'SALDO_ATUALTEXT': 'ТЕКУЩИЙ БАЛАНС:',
            'RECEITASTEXT': 'ДОХОДЫ:',
            'FILTRAR_PROPRIETÁRIOTEXT': 'ФИЛЬТР ПО ВЛАДЕЛЬЦУ',
            'SELECIONE UM PROPRIETÁRIOTEXT': 'ВЫБЕРИТЕ ВЛАДЕЛЬЦА',
            'SALDOS_BANCÁRIOSTEXT': 'БАНКОВСКИЕ ОСТАТКИ',
            'SALDO_TOTALTEXT': 'ОБЩИЙ БАЛАНС:',
            'SALDO ACUMULADO NO FIM DE CADA MÊSTEXT': 'БАЛАНС, НАКОПЛЕННЫЙ В КОНЦЕ КАЖДОГО МЕСЯЦА',
            'AJUSTAR_SALDOTEXT': 'ОТРЕГУЛИРУЙТЕ БАЛАНС',
            'MOSTRAR TODAS AS CONTASTEXT': 'ПОКАЗАТЬ ВСЕ АККАУНТЫ',
            'Inserir_novo_registroTEXT': "Вставить новую запись",
            'DATATEXT': 'ДАТА',
            'SELECIONE_O_BANCOTEXT': "ВЫБЕРИТЕ БАНК",
            'SELECIONE_O_LANÇAMENTOTEXT': "ВЫБОР РЕЛИЗА",
            'INSIRA_O_VALORTEXT': "ВВЕДИТЕ ЗНАЧЕНИЕ",
            'ESTORNOTEXT': "ОБРАТНЫЙ ОТКАЗ",
            'DESCRIÇÃOTEXT': 'ОПИСАНИЕ',
            'SELECIONE_O_PROJETOTEXT': "ВЫБРАТЬ ПРОЕКТ",
            'CONCILIADOTEXT': "ПРИМИРЕННЫЙ",
            'ANALÍTICATEXT': "АНАЛИТИКА",
            'INSERIRTEXT': 'ВСТАВЛЯТЬ',
            'Preencha_todos_os_camposTEXT': "Заполните все поля",
            'Registro_inserido_com_sucessoTEXT': "Запись успешно вставлена!",
            'Editar_registroTEXT': "Редактировать запись",
            'INSERIR_NOVO_LANÇAMENTOTEXT': "ВСТАВЬТЕ НОВЫЙ РЕЛИЗ",
            'Digite_o_IDTEXT': "Введите идентификатор",
            'EDITARTEXT': 'РЕДАКТИРОВАТЬ',
            'DELETARTEXT': 'УДАЛИТЬ',
            'Registro_deletado_com_sucessoTEXT': "Запись успешно удалена!",
            'Registro_editado_com_sucessoTEXT': "Запись успешно отредактирована!",
            'Inserir_nova_transferência_entre_contasTEXT': "Вставить новый перевод между счетами",
            'SELECIONE_O_BANCO_DE_ORIGEMTEXT': "ВЫБЕРИТЕ БАНК-ИСТОЧНИК",
            'SELECIONE_O_BANCO_DE_DESTINOTEXT': "ВЫБЕРИТЕ БАНК НАЗНАЧЕНИЯ",
            'Selecione_contas_diferentesTEXT': "Выбрать разные аккаунты",
        }

    return textos
