def traaducaoapp(language_of_page):
    textos = {}

    if language_of_page == "PORTUGUÊS":
        textos = {
            'DATA_DA_COMPRA_TEXT': 'DATA DA COMPRA',
            'DATA_DA_DESPESA_TEXT': 'DATA DA DESPESA',
            'SEM_LANCAMENTOS_TEXT': 'SEM LANÇAMENTOS',
            'FATURA_TEXT': 'FATURA',
            'NUMERO_DE_PARCELAS_TEXT': 'NÚMERO DE PARCELAS',
            'SELECIONE_O_CARTAO_TEXT': 'SELECIONE O CARTÃO',
            'PAGAR_FATURA_TEXT': 'PAGAR FATURA',
            'DESCONCILIAR_TEXT': 'DESCONCILIAR',
            'CONCILIAR_TEXT': 'CONCILIAR',
            'SELECIONE_A_FATURA_TEXT': 'SELECIONE A FATURA',
            'INSERIR_LANCAMENTOS_TEXT': 'INSERIR LANÇAMENTOS',
            'SELECIONE_TEXT': 'SELECIONE',
            'ALTERACOES_EFETUADAS_TEXT': 'ALTERAÇÕES EFETUADAS',
            'EDITAR_LANCAMENTOS_TEXT': 'EDITAR LANÇAMENTOS',
            'TODOS_OS_LANCAMENTOS_FORAM_CONCILIADOS_TEXT': 'TODOS OS LANÇAMENTOS FORAM CONCILIADOS!',
            'CONCILIAR_TODOS_TEXT': 'CONCILIAR TODOS',
            'VOCE_TEM_LANCAMENTOS_NAO_CONCILIADOS_TEXT': 'VOCÊ TEM LANÇAMENTOS NÃO CONCILIADOS. FAVOR VERIFICAR.',
            'SELECIONE_AS_COLUNAS_DA_TABELA_TEXT': 'SELECIONE AS COLUNAS DA TABELA:',
            'SELECIONE_A_CATEGORIA_TEXT': 'SELECIONE A CATEGORIA',
            'PESQUISAR_DESCRICAO_TEXT': 'PESQUISAR DESCRIÇÃO',
            'CONCILIAR_FATURA': 'CONCILIAR FATURA',
            'VALOR_TOTAL_À_PAGAR' : 'VALOR TOTAL À PAGAR',
            'ESCOLHA_PROJETO_TEXT': "ESCOLHA O PROJETO",
            'DATA INICIAL TEXT': 'DATA INICIAL',
            'DATA FINAL TEXT': 'DATA FINAL',
            'INCLUIR_LANÇAMENTOS_NÃO_CONCILIADOS_TEXT':'INCLUIR LANÇAMENTOS NÃO CONCILIADOS',
            'SALDOS':'SALDOS',
            'LANÇAMENTOS':'LANÇAMENTOS',
            'CONFIGURAÇÕES':'CONFIGURAÇÕES',
            'CARTÕES_DE_CRÉDITO':'CARTÕES DE CRÉDITO',
            'RECEITAS X DESPESAS':'RECEITAS X DESPESAS',
            'VERSÃO':'SOBRE',
            'BEMVINDO': 'BEM-VINDO,',
            'LANCAMENTOS LOCALIZADOS': 'LANÇAMENTO(S) LOCALIZADO(S), DESEJA ALTERAR?',
            'INATIVAS_TEXT':'INATIVAS',
            'ATIVAS_TEXT':'ATIVAS',
            'SELECIONAR_A_ID_TEXT':'SELECIONAR A ID',
            'ATIVAR_TEXT':'ATIVAR',
            'NOVA_CONTA_BANCÁRIA_TEXT':'NOVA CONTA BANCÁRIA',
            'NOME_TEXT':'NOME',
            'PROPRIETÁRIO_TEXT':'PROPRIETÁRIO',
            'INSERIR_TEXT':'INSERIR',
            'INATIVAR_TEXT':'INATIVAR',
            'EDITAR_CONTA_BANCÁRIA_TEXT':'EDITAR CONTA BANCÁRIA',
            'NOME_BANCO_TEXT':'NOME',
            'NOVA_CONTA_BANCÁRIA_TEXT':'NOVA CONTA BANCÁRIA',
            'NOVA_CONTA_CONTÁBIL_TEXT':'NOVA CONTA CONTÁBIL',
            'NOVO_PROJECT_TEXT':'NOVO PROJETO/EVENTO',            
            'CONTA_CONTÁBIL_TEXT':'CONTA CONTÁBIL',
            'CATEGORIA_TEXT':'CATEGORIA',
            'ATRIBUIÇÃO_TEXT':'ATRIBUIÇÃO',
            'EDITAR_CONTA_CONTÁBIL_TEXT':'EDITAR CONTA CONTÁBIL',
            'EDITAR_PROJETO_EVENTO_TEXT':'EDITAR PROJETO/EVENTO',
            'NOVO_CARTÃO_DE_CRÉDITO_TEXT':'NOVO CARTÃO DE CRÉDITO',
            'EDITAR_CARTÃO_DE_CRÉDITO_TEXT':'EDITAR CARTÃO DE CRÉDITO',
            'CONTASBANCARIASTEXT':'CONTAS BANCÁRIAS',
            'CONTASCONTABEISTEXT':'CONTAS CONTÁBEIS',
            'PROJETOS/EVENTOSTEXT':'PROJETOS/EVENTOS',
            'CARTOES_DE_CREDITOTEXT':'CARTÕES DE CRÉDITO',
            'INSERINDO_INFORMAÇÕESTEXT' : 'INSERINDO INFORMAÇÕES',
            'DATA_SALDOTEXT' :'DATA SALDO',
            'SALDO_ATUALTEXT' :'SALDO ATUAL:',
            'RECEITASTEXT' :'RECEITAS:',
            'DESPESATEXT':'DESPESAS',
            'FILTRAR_PROPRIETÁRIOTEXT' :'FILTRAR POR PROPRIETÁRIO',
            'SELECIONE UM PROPRIETÁRIOTEXT' :'SELECIONE UM PROPRIETÁRIO',
            'SALDOS_BANCÁRIOSTEXT' :'SALDOS BANCÁRIOS',
            'SALDO_TOTALTEXT' :'SALDO TOTAL:',
            'SALDO ACUMULADO NO FIM DE CADA MÊSTEXT' :'SALDO ACUMULADO NO FIM DE CADA MÊS',
            'AJUSTAR_SALDOTEXT' :'AJUSTAR SALDO',
            'MOSTRAR TODAS AS CONTASTEXT' :'MOSTRAR TODAS AS CONTAS',
            'Inserir_novo_registroTEXT': 'Inserir novo registro',
            'DATATEXT': 'DATA',
            'SELECIONE_O_BANCOTEXT': 'SELECIONE O BANCO',
            'SELECIONE_O_LANÇAMENTOTEXT': 'SELECIONE O LANÇAMENTO',
            'INSIRA_O_VALORTEXT': 'INSIRA O VALOR',
            'ESTORNOTEXT': 'ESTORNO',
            'DESCRIÇÃOTEXT': 'DESCRIÇÃO',
            'SELECIONE_O_PROJETOTEXT': 'SELECIONE O PROJETO',
            'CONCILIADOTEXT': 'CONCILIADO',
            'ANALÍTICATEXT': 'ANALÍTICA',
            'INSERIRTEXT': 'INSERIR',
            'Preencha_todos_os_camposTEXT': 'PREENCHA TODOS OS CAMPOS',
            'Registro_inserido_com_sucessoTEXT': 'REGISTRO INSERIDO COM SUCESSO!',
            'Editar_registroTEXT': 'EDITAR REGISTRO',
            'INSERIR_NOVO_LANÇAMENTOTEXT': 'INSERIR NOVO LANÇAMENTO',
            'Digite_o_IDTEXT': 'DIGITE O ID',
            'EDITARTEXT': 'EDITAR',
            'DELETARTEXT': 'DELETAR',
            'Registro_deletado_com_sucessoTEXT': 'REGISTRO DELETADO COM SUCESSO!',
            'Registro_editado_com_sucessoTEXT': 'REGISTRO EDITADO COM SUCESSO!',
            'Inserir_nova_transferência_entre_contasTEXT': 'INSERIR NOVA TRANSFERÊNCIA ENTRE CONTAS',
            'SELECIONE_O_BANCO_DE_ORIGEMTEXT': 'SELECIONE O BANCO DE ORIGEM',
            'SELECIONE_O_BANCO_DE_DESTINOTEXT': 'SELECIONE O BANCO DE DESTINO',
            'Selecione_contas_diferentesTEXT': 'SELECIONE CONTAS DIFERENTES',

        }

    elif language_of_page == "ENGLISH":
        textos = {
            'DATA_DA_COMPRA_TEXT': 'PURCHASE DATE',
            'DATA_DA_DESPESA_TEXT': 'EXPENSE DATE',
            'SEM_LANCAMENTOS_TEXT': 'NO ENTRIES',
            'FATURA_TEXT': 'INVOICE',
            'NUMERO_DE_PARCELAS_TEXT': 'NUMBER OF INSTALLMENTS',
            'SELECIONE_O_CARTAO_TEXT': 'SELECT THE CARD',
            'PAGAR_FATURA_TEXT': 'PAY INVOICE',
            'DESCONCILIAR_TEXT': 'UNRECONCILE',
            'CONCILIAR_TEXT': 'RECONCILE',
            'SELECIONE_A_FATURA_TEXT': 'SELECT THE MONTH OF CARD BILL',
            'INSERIR_LANCAMENTOS_TEXT': 'INSERT ENTRIES',
            'SELECIONE_TEXT': 'SELECT',
            'ALTERACOES_EFETUADAS_TEXT': 'CHANGES MADE',
            'EDITAR_LANCAMENTOS_TEXT': 'EDIT ENTRIES',
            'TODOS_OS_LANCAMENTOS_FORAM_CONCILIADOS_TEXT': 'ALL ENTRIES HAVE BEEN RECONCILED!',
            'CONCILIAR_TODOS_TEXT': 'RECONCILE ALL',
            'VOCE_TEM_LANCAMENTOS_NAO_CONCILIADOS_TEXT': 'YOU HAVE UNRECONCILED ENTRIES. PLEASE CHECK.',
            'SELECIONE_AS_COLUNAS_DA_TABELA_TEXT': 'SELECT TABLE COLUMNS:',
            'PESQUISAR_DESCRICAO_TEXT': 'SEARCH DESCRIPTION',
            'SELECIONE_A_CATEGORIA_TEXT': 'SELECT CATEGORY',
            'CONCILIAR_FATURA': 'RECONCILE CARD BILL',
            'VALOR_TOTAL_À_PAGAR' : 'TOTAL AMOUNT TO BE PAID',
            'ESCOLHA_PROJETO_TEXT': "CHOOSE THE PROJECT",
            'DATA INICIAL TEXT': 'START DATE',
            'DATA FINAL TEXT': 'END DATE',
            'INCLUIR_LANÇAMENTOS_NÃO_CONCILIADOS_TEXT':'INCLUDE UNCONCILIATED RELEASES',
            'SALDOS':'BANK BALANCE',
            'LANÇAMENTOS':'BANK ACCOUNTS RECORDS',
            'CONFIGURAÇÕES':'SETTINGS',
            'CARTÕES_DE_CRÉDITO':'CREDIT CARDS',
            'RECEITAS X DESPESAS':'INCOMES X EXPENSES',
            'VERSÃO':'ABOUT',
            'BEMVINDO': 'WELCOME,',
            'LANCAMENTOS LOCALIZADOS': 'RECORDS FOUND, DO YOU WANT TO CHANGE?',
            'INATIVAS_TEXT':'INACTIVE',
            'ATIVAS_TEXT':'ACTIVE',
            'SELECIONAR_A_ID_TEXT':'SELECT ID',
            'ATIVAR_TEXT':'ACTIVATE',
            'NOVA_CONTA_BANCÁRIA_TEXT':'NEW BANK ACCOUNT',
            'NOME_TEXT':'NAME',
            'PROPRIETÁRIO_TEXT':'OWNER',
            'INSERIR_TEXT':'ENTER',
            'INATIVAR_TEXT':'INACTIVATE',
            'EDITAR_CONTA_BANCÁRIA_TEXT':'EDIT BANK ACCOUNT',
            'NOME_BANCO_TEXT':'NAME BANK',
            'NOVA_CONTA_BANCÁRIA_TEXT':'NEW BANK ACCOUNT',
            'NOVA_CONTA_CONTÁBIL_TEXT':'NEW ACCOUNTING ACCOUNT',
            'NOVO_PROJECT_TEXT':'NEW PROJECT/EVENT',
            'CONTA_CONTÁBIL_TEXT':'ACCOUNTING ACCOUNT',
            'CATEGORIA_TEXT':'CATEGORY',
            'ATRIBUIÇÃO_TEXT':'ASSIGNMENT',
            'EDITAR_CONTA_CONTÁBIL_TEXT':'EDIT ACCOUNTING ACCOUNT',
            'EDITAR_PROJETO_EVENTO_TEXT':'EDIT PROJECT/EVENT',
            'NOVO_CARTÃO_DE_CRÉDITO_TEXT':'NEW CREDIT CARD',
            'EDITAR_CARTÃO_DE_CRÉDITO_TEXT':'EDIT CREDIT CARD',
            'CONTASBANCARIASTEXT':'BANK ACCOUNTS',
            'CONTASCONTABEISTEXT':'ACCOUNTING ACCOUNTS',
            'PROJETOS/EVENTOSTEXT':'PROJECTS/EVENTS',
            'CARTOES_DE_CREDITOTEXT':'CREDIT CARDS',
            'INSERINDO_INFORMAÇÕESTEXT' : 'INSERTING DATA',
            'DATA_SALDOTEXT' :'DATE BALANCE',
            'SALDO_ATUALTEXT' :'CURRENT BALANCE:',
            'RECEITASTEXT' :'REVENUES:',
            'DESPESATEXT':'EXPENSES',
            'FILTRAR_PROPRIETÁRIOTEXT' :'FILTER BY OWNER',
            'SELECIONE UM PROPRIETÁRIOTEXT' :'SELECT AN OWNER',
            'SALDOS_BANCÁRIOSTEXT' :'BANK BALANCES',
            'SALDO_TOTALTEXT' :'TOTAL BALANCE:',
            'SALDO ACUMULADO NO FIM DE CADA MÊSTEXT' :'CUMULATIVE BALANCE AT THE END OF EACH MONTH',
            'AJUSTAR_SALDOTEXT' :'ADJUST BALANCE',
            'MOSTRAR TODAS AS CONTASTEXT' :'SHOW ALL ACCOUNTS',
            'Inserir_novo_registroTEXT': 'Insert new ENTRY',
            'DATATEXT': 'DATE',
            'SELECIONE_O_BANCOTEXT': 'SELECT BANK',
            'SELECIONE_O_LANÇAMENTOTEXT': 'SELECT ENTRY',
            'INSIRA_O_VALORTEXT': 'ENTER VALUE',
            'ESTORNOTEXT': 'REVERSAL',
            'DESCRIÇÃOTEXT': 'DESCRIPTION',
            'SELECIONE_O_PROJETOTEXT': 'SELECT PROJECT',
            'CONCILIADOTEXT': 'CONCILIATED',
            'ANALÍTICATEXT': 'ANALYTICS',
            'INSERIRTEXT': 'INSERT',
            'Preencha_todos_os_camposTEXT': 'FILL IN ALL FIELDS',
            'Registro_inserido_com_sucessoTEXT': 'RECORD INSERTED SUCCESSFULLY!',
            'Editar_registroTEXT': 'EDIT RECORD',
            'INSERIR_NOVO_LANÇAMENTOTEXT': 'INSERT NEW ENTRY',
            'Digite_o_IDTEXT': 'ENTER ID',
            'EDITARTEXT': 'EDIT',
            'DELETARTEXT': 'DELETE',
            'Registro_deletado_com_sucessoTEXT': 'RECORD DELETED SUCCESSFULLY!',
            'Registro_editado_com_sucessoTEXT': 'RECORD EDITED SUCCESSFULLY!',
            'Inserir_nova_transferência_entre_contasTEXT': 'INSERT NEW TRANSFER BETWEEN ACCOUNTS',
            'SELECIONE_O_BANCO_DE_ORIGEMTEXT': 'SELECT SOURCE BANK',
            'SELECIONE_O_BANCO_DE_DESTINOTEXT': 'SELECT DESTINATION BANK',
            'Selecione_contas_diferentesTEXT': 'SELECT DIFFERENT ACCOUNTS',

        }

    elif language_of_page == "РУССКИЙ":
        textos = {
            'DATA_DA_COMPRA_TEXT': 'ДАТА ПОКУПКИ',
            'DATA_DA_DESPESA_TEXT': 'ДАТА РАСХОДА',
            'SEM_LANCAMENTOS_TEXT': 'БЕЗ ЗАПИСЕЙ',
            'FATURA_TEXT': 'СЧЁТ-ФАКТУРА',
            'NUMERO_DE_PARCELAS_TEXT': 'КОЛИЧЕСТВО ВЗНОСОВ',
            'SELECIONE_O_CARTAO_TEXT': 'ВЫБЕРИТЕ КАРТУ',
            'PAGAR_FATURA_TEXT': 'ОПЛАТИТЬ СЧЁТ-ФАКТУРУ',
            'DESCONCILIAR_TEXT': 'ОТМЕНИТЬ СВЕРКУ',
            'CONCILIAR_TEXT': 'СВЕРИТЬ',
            'SELECIONE_A_FATURA_TEXT': 'ВЫБЕРИТЕ СЧЁТ-ФАКТУРУ',
            'INSERIR_LANCAMENTOS_TEXT': 'ДОБАВИТЬ ЗАПИСИ',
            'SELECIONE_TEXT': 'ВЫБЕРИТЕ',
            'ALTERACOES_EFETUADAS_TEXT': 'ИЗМЕНЕНИЯ ВНЕСЕНЫ',
            'EDITAR_LANCAMENTOS_TEXT': 'РЕДАКТИРОВАТЬ ЗАПИСИ',
            'TODOS_OS_LANCAMENTOS_FORAM_CONCILIADOS_TEXT': 'ВСЕ ЗАПИСИ БЫЛИ СВЕРЕНЫ!',
            'CONCILIAR_TODOS_TEXT': 'СВЕРИТЬ ВСЁ',
            'VOCE_TEM_LANCAMENTOS_NAO_CONCILIADOS_TEXT': 'У ВАС ЕСТЬ НЕСВЕРЕННЫЕ ЗАПИСИ. ПОЖАЛУЙСТА, ПРОВЕРЬТЕ.',
            'SELECIONE_AS_COLUNAS_DA_TABELA_TEXT': 'ВЫБЕРИТЕ СТОЛБЦЫ ТАБЛИЦЫ:',
            'PESQUISAR_DESCRICAO_TEXT': 'ПОИСК ОПИСАНИЯ',
            'SELECIONE_A_CATEGORIA_TEXT': 'ВЫБЕРИТЕ КАТЕГОРИЮ',
            'CONCILIAR_FATURA': 'СВЕРИТЬ СЧЕТ ПО КАРТОЧКЕ',
            'VALOR_TOTAL_À_PAGAR' : 'ОБЩАЯ СУММА К ОПЛАТЕ',
            'ESCOLHA_PROJETO_TEXT': "ВЫБЕРИТЕ ПРОЕКТ",
            'DATA INICIAL TEXT': 'ДАТА НАЧАЛА',
            'DATA FINAL TEXT': 'ДАТА ОКОНЧАНИЯ',
            'INCLUIR_LANÇAMENTOS_NÃO_CONCILIADOS_TEXT':'ВКЛЮЧАЙТЕ НЕСОГЛАСОВАННЫЕ РЕЛИЗЫ',
            'SALDOS':'БАНК БАЛАНС',
            'LANÇAMENTOS':'ЗАПИСИ БАНКОВСКИХ СЧЕТОВ',
            'CONFIGURAÇÕES':'НАСТРОЙКИ',
            'CARTÕES_DE_CRÉDITO':'КРЕДИТНЫЕ КАРТЫ',
            'RECEITAS X DESPESAS':'ДОХОДЫ X РАСХОДЫ',
            'VERSÃO':'О',
            'BEMVINDO': 'ДОБРО ПОЖАЛОВАТЬ,',
            'LANCAMENTOS LOCALIZADOS': 'РЕЛИЗОВ, ХОТИТЕ ИЗМЕНИТЬ?',
            'INATIVAS_TEXT':'НЕАКТИВНЫЙ',
            'ATIVAS_TEXT':'АКТИВНЫЙ',
            'SELECIONAR_A_ID_TEXT':'ВЫБЕРИТЕ ИДЕНТИФИКАТОР',
            'ATIVAR_TEXT':'АКТИВИРОВАТЬ',
            'NOVA_CONTA_BANCÁRIA_TEXT':'НОВЫЙ БАНКОВСКИЙ СЧЕТ',
            'NOME_TEXT':'ИМЯ',
            'PROPRIETÁRIO_TEXT':'ВЛАДЕЛЕЦ',
            'INSERIR_TEXT':'ВСТАВЛЯТЬ',
            'INATIVAR_TEXT':'ДЕАКТИВИРОВАТЬ',
            'EDITAR_CONTA_BANCÁRIA_TEXT':'ИЗМЕНИТЬ БАНКОВСКИЙ СЧЕТ',
            'NOME_BANCO_TEXT':'НАЗВАНИЕ БАНКА',
            'NOVA_CONTA_BANCÁRIA_TEXT':'НОВЫЙ БАНКОВСКИЙ СЧЕТ',
            'NOVA_CONTA_CONTÁBIL_TEXT':'НОВЫЙ БУХГАЛТЕРСКИЙ СЧЕТ',
            'NOVO_PROJECT_TEXT':'НОВЫЙ ПРОЕКТ/СОБЫТИЕ',            
            'CONTA_CONTÁBIL_TEXT':'БУХГАЛТЕРСКИЙ СЧЕТ',
            'CATEGORIA_TEXT':'КАТЕГОРИЯ',
            'ATRIBUIÇÃO_TEXT':'АТРИБУЦИЯ',
            'EDITAR_CONTA_CONTÁBIL_TEXT':'РЕДАКТИРОВАТЬ БУХГАЛТЕРСКИЙ СЧЕТ',
            'EDITAR_PROJETO_EVENTO_TEXT':'РЕДАКТИРОВАТЬ ПРОЕКТ/СОБЫТИЕ',
            'NOVO_CARTÃO_DE_CRÉDITO_TEXT':'НОВАЯ КРЕДИТНАЯ КАРТА',
            'EDITAR_CARTÃO_DE_CRÉDITO_TEXT':'ИЗМЕНИТЬ КРЕДИТНУЮ КАРТУ',
            'CONTASBANCARIASTEXT':'БАНКОВСКИЕ СЧЕТА',
            'CONTASCONTABEISTEXT':'БУХГАЛТЕРСКИЕ СЧЕТА',
            'PROJETOS/EVENTOSTEXT':'ПРОЕКТЫ/СОБЫТИЯ',
            'CARTOES_DE_CREDITOTEXT':'КРЕДИТНЫЕ КАРТЫ',
            'INSERINDO_INFORMAÇÕESTEXT' : 'ВСТАВКА ИНФОРМАЦИИ',
            'DATA_SALDOTEXT': 'ДАТА БАЛАНСА',
            'SALDO_ATUALTEXT': 'ТЕКУЩИЙ БАЛАНС:',
            'RECEITASTEXT': 'ДОХОДЫ:',
            'DESPESATEXT':'ЗАТРАТЫ',
            'FILTRAR_PROPRIETÁRIOTEXT': 'ФИЛЬТР ПО ВЛАДЕЛЬЦУ',
            'SELECIONE UM PROPRIETÁRIOTEXT': 'ВЫБЕРИТЕ ВЛАДЕЛЬЦА',
            'SALDOS_BANCÁRIOSTEXT': 'БАНКОВСКИЕ ОСТАТКИ',
            'SALDO_TOTALTEXT': 'ОБЩИЙ БАЛАНС:',
            'SALDO ACUMULADO NO FIM DE CADA MÊSTEXT': 'БАЛАНС, НАКОПЛЕННЫЙ В КОНЦЕ КАЖДОГО МЕСЯЦА',
            'AJUSTAR_SALDOTEXT': 'ОТРЕГУЛИРУЙТЕ БАЛАНС',
            'MOSTRAR TODAS AS CONTASTEXT': 'ПОКАЗАТЬ ВСЕ АККАУНТЫ',
            'Inserir_novo_registroTEXT': "Вставить новую запись",
            'DATATEXT': 'ДАТА',
            'SELECIONE_O_BANCOTEXT': "ВЫБЕРИТЕ БАНК",
            'SELECIONE_O_LANÇAMENTOTEXT': "ВЫБОР РЕЛИЗА",
            'INSIRA_O_VALORTEXT': "ВВЕДИТЕ ЗНАЧЕНИЕ",
            'ESTORNOTEXT': "ОБРАТНЫЙ ОТКАЗ",
            'DESCRIÇÃOTEXT': 'ОПИСАНИЕ',
            'SELECIONE_O_PROJETOTEXT': "ВЫБРАТЬ ПРОЕКТ",
            'CONCILIADOTEXT': "ПРИМИРЕННЫЙ",
            'ANALÍTICATEXT': "АНАЛИТИКА",
            'INSERIRTEXT': 'ВСТАВЛЯТЬ',
            'Preencha_todos_os_camposTEXT': "ЗАПОЛНИТЕ ВСЕ ПОЛЯ",
            'Registro_inserido_com_sucessoTEXT': "ЗАПИСЬ УСПЕШНО ВСТАВЛЕНА!",
            'Editar_registroTEXT': "РЕДАКТИРОВАТЬ ЗАПИСЬ",
            'INSERIR_NOVO_LANÇAMENTOTEXT': "ВСТАВЬТЕ НОВЫЙ РЕЛИЗ",
            'Digite_o_IDTEXT': "ВВЕДИТЕ ИДЕНТИФИКАТОР",
            'EDITARTEXT': 'РЕДАКТИРОВАТЬ',
            'DELETARTEXT': 'УДАЛИТЬ',
            'Registro_deletado_com_sucessoTEXT': "ЗАПИСЬ УСПЕШНО УДАЛЕНА!",
            'Registro_editado_com_sucessoTEXT': "ЗАПИСЬ УСПЕШНО ОТРЕДАКТИРОВАНА!",
            'Inserir_nova_transferência_entre_contasTEXT': "ВСТАВИТЬ НОВЫЙ ПЕРЕВОД МЕЖДУ СЧЕТАМИ",
            'SELECIONE_O_BANCO_DE_ORIGEMTEXT': "ВЫБЕРИТЕ БАНК-ИСТОЧНИК",
            'SELECIONE_O_BANCO_DE_DESTINOTEXT': "ВЫБЕРИТЕ БАНК НАЗНАЧЕНИЯ",
            'Selecione_contas_diferentesTEXT': "ВЫБРАТЬ РАЗНЫЕ АККАУНТЫ",
        }

    return textos
